name: "sos"
shortDesc: "Plugin for gathering various types of data from OpenShift."
command: "./sos.sh"
flags:
  - name: "output"
    desc: "Output format of data (json [default] or yaml)."
    shorthand: "o"
    defValue: "json"
