name: "sos"
shortDesc: "Plugin for gathering various types of data from OpenShift."
command: "./sos.sh"
flags:
  - name: "output"
    desc: "Output format of data (json [default] or yaml)."
    shorthand: "o"
    defValue: "json"
  - name: "include-secret"
    desc: "Dump secret (true [default] or false)"
    defValue: "true"
  - name: "include-configmap"
    desc: "Dump configmap (true [default] or false)"
    defValue: "true"
